# -*- coding: utf-8 -*-
"""lgbm_risk_reward.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V923OusrYG2IAbyYmBTuPJ_vttAMt3dH
"""

import matplotlib.pyplot as plt
import pandas as pd
import lightgbm as lgb

from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split

df = pd.read_csv("EURUSD_Daily_197101040000_202009010000.csv", sep='\t')
df.head()

from pandas import to_datetime
df['<DATE>'] = to_datetime(df['<DATE>'])
df.tail()

df['shifted_high'] = df['<HIGH>'].shift(periods=-1)
df['shifted_low'] = df['<LOW>'].shift(periods=-1)
df = df.head(-1)
df = df[['<DATE>','<OPEN>','<HIGH>','<LOW>','<CLOSE>','<TICKVOL>','<VOL>','<SPREAD>','shifted_high','shifted_low']]
df.tail()

# from sklearn.preprocessing import MinMaxScaler
# #scale the training df
# scaler = MinMaxScaler()
# scaled = scaler.fit_transform(df)
# scaled_train = pd.DataFrame(scaled)
# scaled_train

#fit df to model
model = LGBMRegressor()
features = ['<OPEN>','<HIGH>','<LOW>','<CLOSE>','<TICKVOL>','<VOL>','<SPREAD>']
target1 = 'shifted_high'
target2 = 'shifted_low'
train = df

model.fit(train[features],train[target1])
print('For risk:reward tomorrow high is')
predicted = model.predict([[1.19112,1.19285,1.18220,1.18547,53643,0,1]]) 
print(predicted)

model.fit(train[features],train[target2])
print('For risk:reward tomorrow low is')
predicted = model.predict([[1.19112,1.19285,1.18220,1.18547,53643,0,1]]) 
predicted